# -*- coding: utf-8 -*-
# We have dependencies to odoo voip for now because alexandre want to hide this, but later we can remove it
{
    "name": "GreenLOC CRM ext",
    "version": "1.0",
    'author': 'Falinwa Randy',
    "description": """
    Module to add additional functionality on CRM based on greenloc
    """,
    "depends": [
        'base',
        'crm',
        'crm_lead_firstname',
        'fal_country_phonenumber',
        'base_geolocalize',
        ],
    'init_xml': [],
    'update_xml': [
        'security/crm_security.xml',
        'security/ir.model.access.csv',
        'report/greenloc_crm_report_contract.xml',
        'report/greenloc_crm_report_3_lodger.xml',
        'report/greenloc_crm_report_3_owner.xml',
        'report/greenloc_crm_report_6_married_multiple.xml',
        'report/greenloc_crm_report_6_married_one.xml',
        'report/greenloc_crm_report_6_widower_multiple.xml',
        'report/greenloc_crm_report_6_widower_one.xml',
        'report/greenloc_crm_report_8_married_multi.xml',
        'report/greenloc_crm_report_8_married_1owner.xml',
        'report/greenloc_crm_report_8_singlewidow_multi.xml',
        'report/greenloc_crm_report_8_singlewidow_1owner.xml',
        'report/greenloc_crm_report_7.xml',
        'report/greenloc_crm_report_9.xml',
        'report/greenloc_crm_report_10.xml',
        'report/greenloc_universign_single_no_lodger.xml',
        'report/greenloc_universign_single_with_lodger.xml',
        'report/greenloc_universign_multi_no_lodger.xml',
        'report/greenloc_universign_multi_with_lodger.xml',
        'report/greenloc_universign_l3_single_no_lodger.xml',
        'report/greenloc_universign_l3_single_with_lodger.xml',
        'report/greenloc_universign_l3_multi_no_lodger.xml',
        'report/greenloc_universign_l3_multi_with_lodger.xml',
        'wizard/crm_docs_upload_signed_views.xml',
        'wizard/crm_merge_opportunities_views.xml',
        'wizard/crm_re_send_model1_mail.xml',
        'data/crm_data.xml',
        'data/report_data.xml',
        'data/opportunity_email_template.xml',
        'data/universign_email_template.xml',
        'data/opportunity_lost_email_template.xml',
        'data/lead_pdf_request_email_template.xml',
        'data/lead_to_affected_email_template.xml',
        'data/opportunity_to_appointment_email_template.xml',
        'data/opportunity_to_won_email_template.xml',
        'views/crm_lead_view.xml',
        'views/res_partner_view.xml',
        'views/res_users_view.xml',
        'views/crm_lead_docs_sign_attachment.xml',
        'views/crm_lead_operator_form.xml',
        'views/crm_roof_information_view.xml',
        'views/crm_technical_visit_view.xml',
    ],
    'css': [],
    'js': [],
    'installable': True,
    'qweb': [
        "static/src/xml/*.xml",
        ],
    'active': False,
    'application': False,
}
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
